
import React from 'react';
import { BarChart2, FileDown } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { revenueByCountryData, shipmentsByCourierData } from '../constants';

const ReportCard: React.FC<{ title: string; description: string }> = ({ title, description }) => (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <div className="flex items-start justify-between">
            <div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">{title}</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">{description}</p>
            </div>
            <BarChart2 className="w-8 h-8 text-blue-500" />
        </div>
        <div className="mt-6 flex items-center gap-2">
            <button className="flex items-center gap-2 text-sm px-3 py-1.5 bg-blue-600 text-white rounded-md hover:bg-blue-700">
                <FileDown size={16} /> PDF
            </button>
            <button className="flex items-center gap-2 text-sm px-3 py-1.5 bg-green-600 text-white rounded-md hover:bg-green-700">
                <FileDown size={16} /> Excel
            </button>
            <button className="flex items-center gap-2 text-sm px-3 py-1.5 bg-gray-600 text-white rounded-md hover:bg-gray-700">
                <FileDown size={16} /> CSV
            </button>
        </div>
    </div>
);

const Reports: React.FC = () => {
    return (
        <div className="space-y-6">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Reports & Analytics</h2>
            
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                 <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
                    <h3 className="text-lg font-semibold mb-4 text-gray-900 dark:text-white">Revenue by Country</h3>
                    <ResponsiveContainer width="100%" height={300}>
                        <BarChart data={revenueByCountryData}>
                            <XAxis dataKey="name" stroke="rgb(107 114 128)" />
                            <YAxis stroke="rgb(107 114 128)" />
                            <Tooltip contentStyle={{ backgroundColor: 'rgb(31 41 55)', border: 'none', color: '#fff' }} cursor={{fill: 'rgba(107, 114, 128, 0.1)'}}/>
                            <Legend />
                            <Bar dataKey="value" name="Revenue ($)" fill="#3b82f6" />
                        </BarChart>
                    </ResponsiveContainer>
                </div>
                 <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
                    <h3 className="text-lg font-semibold mb-4 text-gray-900 dark:text-white">Shipments by Courier</h3>
                     <ResponsiveContainer width="100%" height={300}>
                        <BarChart data={shipmentsByCourierData}>
                            <XAxis dataKey="name" stroke="rgb(107 114 128)" />
                            <YAxis stroke="rgb(107 114 128)"/>
                            <Tooltip contentStyle={{ backgroundColor: 'rgb(31 41 55)', border: 'none', color: '#fff' }} cursor={{fill: 'rgba(107, 114, 128, 0.1)'}}/>
                            <Legend />
                            <Bar dataKey="value" name="Shipments" fill="#8b5cf6" />
                        </BarChart>
                    </ResponsiveContainer>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <ReportCard title="Daily Shipments" description="Track all shipments created today." />
                <ReportCard title="Invoice Aging" description="See outstanding and overdue invoices." />
                <ReportCard title="Customer Payments" description="History of all payments by customer." />
                <ReportCard title="Shipped Medicines" description="Analysis of medicine categories." />
                <ReportCard title="Profit Margin" description="Breakdown of profit per shipment." />
                <ReportCard title="Country Revenue" description="Total revenue generated by country." />
            </div>
        </div>
    );
};

export default Reports;
